name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Setup libfuse
        run: sudo apt-get install -y libfuse-dev
        
      - name: Build
        run: go build
        env:
          GOOS: windows
          GOARCH: amd64
      
      - name: Create package
        uses: actions/upload-artifact@v2
        with:
          name: git-fuse-windows-amd64
          path: git-fuse.exe
        
      - name: Build
        run: go build
        env:
          GOOS: windows
          GOARCH: amd64
          CGO_ENABLED: 0
      
      - name: Create package
        uses: actions/upload-artifact@v2
        with:
          name: git-fuse-windows-amd64-nocgo
          path: git-fuse.exe
        
      - name: Build
        run: go build
        env:
          GOOS: linux
          GOARCH: amd64
      
      - name: Create package
        uses: actions/upload-artifact@v2
        with:
          name: git-fuse-linux-amd64
          path: git-fuse
        
      - name: Build
        run: go build
        env:
          GOOS: linux
          GOARCH: arm64
      
      - name: Create package
        uses: actions/upload-artifact@v2
        with:
          name: git-fuse-darwin-amd64
          path: git-fuse
      