name: Build
on:
  push:
    branches:
      - master

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: '1.19'

      - name: Setup libfuse
        run: sudo apt-get install -y libfuse-dev
        
      - name: Build
        run: go build
        env:
          GOOS: linux
          GOARCH: amd64

      - name: Create package
        uses: actions/upload-artifact@v3
        with:
          name: git-fuse-linux-amd64
          path: git-fuse

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: '1.19'

      - name: Setup libfuse
        run: choco install winfsp -y --no-progress
        
      - name: Build
        run: go build
        env:
          GOOS: windows
          GOARCH: amd64
          CPATH: C:\Program Files (x86)\WinFsp\inc\fuse
      
      - name: Create package
        uses: actions/upload-artifact@v3
        with:
          name: git-fuse-windows-amd64
          path: git-fuse.exe
        
      - name: Build
        run: go build
        env:
          GOOS: windows
          GOARCH: amd64
          CGO_ENABLED: 0
      
      - name: Create package
        uses: actions/upload-artifact@v3
        with:
          name: git-fuse-windows-amd64-nocgo
          path: git-fuse.exe

  build_mac:
    name: Build Mac
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: '1.19'

      - name: Setup libfuse
        run: |
          brew update
          brew install homebrew/cask/osxfuse
        
      - name: Build
        run: go build
        env:
          GOOS: darwin
          GOARCH: amd64
      
      - name: Create package
        uses: actions/upload-artifact@v3
        with:
          name: git-fuse-darwin-amd64
          path: git-fuse
        
      
