name: Build
on:
  push:
    branches:
      - master

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Setup libfuse
        run: sudo apt-get install -y libfuse-dev
        
      - name: Build
        run: go build
        env:
          GOOS: linux
          GOARCH: amd64

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Setup libfuse
        run: choco install winfsp --version=1.0.17072 -y
        
      - name: Build
        run: go build
        env:
          GOOS: windows
          GOARCH: amd64
      
      - name: Create package
        uses: actions/upload-artifact@v2
        with:
          name: git-fuse-windows-amd64
          path: git-fuse.exe
        
      - name: Build
        run: go build
        env:
          GOOS: windows
          GOARCH: amd64
          CGO_ENABLED: 0
      
      - name: Create package
        uses: actions/upload-artifact@v2
        with:
          name: git-fuse-windows-amd64-nocgo
          path: git-fuse.exe

  build_mac:
    name: Build Mac
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Setup libfuse
        run: |
          brew update
          brew install caskroom/cask/osxfuse
      
      - name: Create package
        uses: actions/upload-artifact@v2
        with:
          name: git-fuse-darwin-amd64
          path: git-fuse
      
      - name: Create package
        uses: actions/upload-artifact@v2
        with:
          name: git-fuse-darwin-arm64
          path: git-fuse
      